(deftheme AzureDarkness
  "A colorful dark theme")

(custom-theme-set-faces
 'AzureDarkness
 '(default ((t (:foreground "#888888" :background "black"))))
 '(cursor ((t (:background "SpringGreen2"))))
 '(fixed-pitch ((t nil)))
 '(variable-pitch ((t (:family "EB Garamond"))))
 '(escape-glyph ((t (:foreground "magenta"))))
 '(minibuffer-prompt ((t (:foreground "aquamarine2"))))
 '(highlight ((t (:background "gray14"))))
 '(region ((t (:background "blue4"))))
 '(shadow ((t (:foreground "gray45"))))
 '(secondary-selection ((t (:background "DarkOrchid4"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "deep pink"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "green4"))))
 '(font-lock-comment-face ((t (:foreground "green3" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "dark violet"))))
 '(font-lock-doc-face ((t (:foreground "cyan3" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "firebrick3"))))
 '(font-lock-keyword-face ((t (:foreground "gold" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "gray80" :weight ultra-bold))))
 '(font-lock-preprocessor-face ((t (:foreground "yellow green" :slant oblique))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "yellow"))))
 '(font-lock-type-face ((t (:foreground "coral"))))
 '(font-lock-variable-name-face ((t (:foreground "DarkOrange1"))))
 '(font-lock-warning-face ((t (:background "DarkOrange4" :foreground "gold1" :weight bold))))
 '(button ((t (:inherit nil :background "blue4" :foreground "DeepPink1" :box 2))))
 '(link ((t (:foreground "dark turquoise" :underline t))))
 '(link-visited ((t (:inherit link :foreground "blue2"))))
 '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
 '(header-line ((t (:inherit mode-line :background "dark red" :foreground "grey90" :box nil))))
 '(tooltip ((t (:inherit variable-pitch :background "gray10" :foreground "PaleGreen1"))))
 '(mode-line ((t (:background "midnight blue" :foreground "SpringGreen2" :box (:line-width -1 :style released-button)))))
 '(mode-line-inactive ((t (:background "gray10" :foreground "gray40" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(isearch ((t (:background "dark green" :foreground "gray96"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((t (:background "purple4" :foreground "gray80"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(error ((t (:background "red4" :foreground "yellow1" :weight bold)))))

(provide-theme 'AzureDarkness)
